version: '3.8'

services:
    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000"  # MinIO API
            - "9001:9001"  # MinIO Web UI
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: admin123
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "8080:8080"
        environment:
            - MINIO_URL=http://minio:9000
            - MINIO_ACCESS_KEY=admin
            - MINIO_SECRET_KEY=admin123
        depends_on:
            - minio

volumes:
    minio_data:
        driver: local