version: '3.8'

services:
    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - MINIO_URL=${MINIO_URL}
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
            - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
        depends_on:
            - minio

volumes:
    minio_data:
        driver: local