spring:
    application:
        name: movies
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: myMovieDB
            auto-index-creation: true
minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:admin}
    secret-key: ${MINIO_SECRET_KEY:admin123}รณ