spring:
    application:
        name: movies
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: myMovieDB
            auto-index-creation: true
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 30MB

minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:admin}
    secret-key: ${MINIO_SECRET_KEY:admin123}

logging:
    level:
      org:
          springframework:
              data:
                  mongodb:
                      core:
                          MongoTemplate: DEBUG
jwt:
    secret: ${JWT_SECRET}
    expiration-time: 86400000